<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('gestorvooheader');

$voos = Data::get('voos');
$aeroportos = Data::get('aeroportos');

Debug::barDump('yolo');
Debug::barDump($aeroportos); 
die;
?>

<div class="container">
    <div class="row">
    <form action="<?=URL::toRoute('voo/update') ?>" method="post">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h1><label for="origem" class="form-label" style="color:black;">Insira o aeroporto de origem</label></h1>
            <select name="idAeroportoOrigem" required style="font-size:22px;">
                <option disabled selected value="teste"> -- select an option -- </option>
                <?php foreach($aeroportos as $aeroporto){?>
                        <option value="<?=$aeroporto->id?>"><?=$aeroporto->nome?></option>
                    <?php }?>
            </select>

        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h1><label for="origem" class="form-label" style="color:black;">Insira o aeroporto de destino</label></h1>
            <select name="idAeroportoDestino" required style="font-size:22px;">
                <option disabled selected value> -- select an option -- </option>
                <?php foreach($aeroportos as $aeroporto){?>
                        <option value="<?=$aeroporto->id?>"><?=$aeroporto->nome?></option>
                    <?php }?>
            </select>

        </div>       
        <div class="col-12 text-right">
        <br><br>
			<button class="btn btn-action" type="submit">Criar</button>
		</div>
    </form>
    </div>

</div>
